import Foundation
import HTTPTypes

let version = "0.0.1"

extension HTTPFields {
  /// The default set of `HTTPFields` used by HTTPClient. Includes `Accept-Encoding`, `Accept-Language`, and `User-Agent`.
  public static let `default`: HTTPFields = {
    var fields = HTTPFields()
    let defaults = [
      HTTPField.defaultAcceptEncoding,
      HTTPField.defaultAcceptLanguage,
      HTTPField.defaultUserAgent,
    ]

    for d in defaults {
      fields.append(d)
    }

    return fields
  }()
}

extension HTTPField {
  /// Returns  default `Accept-Encoding` header.
  public static let defaultAcceptEncoding = HTTPField(
    name: .acceptEncoding, value: ["br", "gzip", "deflate"].qualityEncoded())

  /// Returns default `Accept-Language` header, generated by querying `Locale` for the user's `preferredLanguages`.
  public static let defaultAcceptLanguage = HTTPField(
    name: .acceptLanguage, value: Locale.preferredLanguages.prefix(6).qualityEncoded())

  /// Example: `iOS Example/1.0 (dev.grds.iOS-Example; build:1; iOS 13.0.0) swift-http-client/1.0.0`
  public static let defaultUserAgent: HTTPField = {
    let info = Bundle.main.infoDictionary
    let executable =
      (info?["CFBundleExecutable"] as? String)
      ?? (ProcessInfo.processInfo.arguments.first?.split(separator: "/").last.map(String.init))
      ?? "Unknown"
    let bundle = info?["CFBundleIdentifier"] as? String ?? "Unknown"
    let appVersion = info?["CFBundleShortVersionString"] as? String ?? "Unknown"
    let appBuild = info?["CFBundleVersion"] as? String ?? "Unknown"

    let osNameVersion: String = {
      let version = ProcessInfo.processInfo.operatingSystemVersion
      let versionString = "\(version.majorVersion).\(version.minorVersion).\(version.patchVersion)"
      let osName: String = {
        #if os(iOS)
          #if targetEnvironment(macCatalyst)
            return "macOS(Catalyst)"
          #else
            return "iOS"
          #endif
        #elseif os(watchOS)
          return "watchOS"
        #elseif os(tvOS)
          return "tvOS"
        #elseif os(macOS)
          return "macOS"
        #elseif os(Linux)
          return "Linux"
        #elseif os(Windows)
          return "Windows"
        #else
          return "Unknown"
        #endif
      }()

      return "\(osName) \(versionString)"
    }()

    let alamofireVersion = "swift-http-client/\(version)"

    let userAgent =
      "\(executable)/\(appVersion) (\(bundle); build:\(appBuild); \(osNameVersion)) \(alamofireVersion)"

    return .init(name: .userAgent, value: userAgent)
  }()
}

extension Collection where Element == String {
  func qualityEncoded() -> String {
    enumerated().map { index, encoding in
      let quality = 1.0 - (Double(index) * 0.1)
      return "\(encoding);q=\(quality)"
    }.joined(separator: ", ")
  }
}
