import Foundation
import HTTPTypes

public struct DefaultHeadersMiddleware: ClientMiddleware {

  let headers = HTTPFields([
    HTTPField.defaultUserAgent,
    HTTPField.defaultAcceptEncoding,
    HTTPField.defaultAcceptLanguage,
  ])

  public func intercept(
    _ request: HTTPRequest,
    body: sending HTTPBody?,
    baseURL: URL,
    next: (HTTPRequest, sending HTTPBody?, URL) async throws -> (HTTPResponse, HTTPBody?)
  ) async throws -> (HTTPResponse, HTTPBody?) {
    var request = request
    for field in headers {
      if !request.headerFields.contains(field.name) {
        request.headerFields[field.name] = field.value
      }
    }
    return try await next(request, body, baseURL)
  }
}

extension HTTPField {
  /// Returns default `Accept-Encoding` header, appropriate for the encodings supported by particular OS versions.
  ///
  /// See the [Accept-Encoding HTTP header documentation](https://tools.ietf.org/html/rfc7230#section-4.2.3) .
  static let defaultAcceptEncoding: HTTPField = {
    let encodings = ["gzip", "deflate"]
    return HTTPField(name: .acceptEncoding, value: encodings.qualityEncoded())
  }()

  /// Returns default `Accept-Language` header, generated by querying `Locale` for the user's `preferredLanguages`.
  ///
  /// See the [Accept-Language HTTP header documentation](https://tools.ietf.org/html/rfc7231#section-5.3.5).
  static let defaultAcceptLanguage: HTTPField = HTTPField(
    name: .acceptLanguage, value: Locale.preferredLanguages.prefix(6).qualityEncoded())

  /// Returns default `User-Agent` header.
  ///
  /// See the [User-Agent header documentation](https://tools.ietf.org/html/rfc7231#section-5.5.3).
  ///
  /// Example: `iOS Example/1.0 (dev.grds.swift-http-client.iOS-Example; build:1; iOS 16.0.0) swift-http-client/1.0.0`
  static let defaultUserAgent: HTTPField = {
    let info = Bundle.main.infoDictionary
    let executable =
      (info?["CFBundleExecutable"] as? String)
      ?? (ProcessInfo.processInfo.arguments.first?.split(separator: "/").last.map(String.init))
      ?? "Unknown"
    let bundle = info?["CFBundleIdentifier"] as? String ?? "Unknown"
    let appVersion = info?["CFBundleShortVersionString"] as? String ?? "Unknown"
    let appBuild = info?["CFBundleVersion"] as? String ?? "Unknown"

    let osNameVersion: String = {
      let version = ProcessInfo.processInfo.operatingSystemVersion
      let versionString = "\(version.majorVersion).\(version.minorVersion).\(version.patchVersion)"
      let osName: String = {
        #if os(iOS)
          #if targetEnvironment(macCatalyst)
            return "macOS(Catalyst)"
          #else
            return "iOS"
          #endif
        #elseif os(watchOS)
          return "watchOS"
        #elseif os(tvOS)
          return "tvOS"
        #elseif os(macOS)
          #if targetEnvironment(macCatalyst)
            return "macOS(Catalyst)"
          #else
            return "macOS"
          #endif
        #elseif os(visionOS)
          return "visionOS"
        #elseif os(Linux)
          return "Linux"
        #elseif os(Windows)
          return "Windows"
        #elseif os(Android)
          return "Android"
        #elseif os(WASI)
          return "WASI"
        #else
          return "Unknown"
        #endif
      }()

      return "\(osName) \(versionString)"
    }()

    let userAgent =
      "\(executable)/\(appVersion) (\(bundle); build:\(appBuild); \(osNameVersion)) swift-http-client/\(version)"

    return HTTPField(name: .userAgent, value: userAgent)
  }()
}

extension Collection<String> {
  func qualityEncoded() -> String {
    enumerated().map { index, encoding in
      let quality = 1.0 - (Double(index) * 0.1)
      return "\(encoding);q=\(quality)"
    }.joined(separator: ", ")
  }
}
