name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  library:
    name: macOS
    strategy:
      matrix:
        xcode: ["16.4", "26.0"]
        config: ["debug", "release"]
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "stable"
      - name: Start httpbingo.org in background
        run: |
          go run github.com/mccutchen/go-httpbin/v2/cmd/go-httpbin@latest -host 127.0.0.1 -port 8081 &
          echo $! > /tmp/httpbingo.pid
          sleep 2
      - name: Run ${{ matrix.config }} tests
        run: swift test -c ${{ matrix.config }}
      - name: Stop httpbingo.org
        if: always()
        run: |
          if [ -f /tmp/httpbingo.pid ]; then
            kill $(cat /tmp/httpbingo.pid) || true
            rm /tmp/httpbingo.pid
          fi

  linux:
    name: Linux
    strategy:
      matrix:
        swift:
          - "6.2"
    runs-on: ubuntu-latest
    container: swift:${{ matrix.swift }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build
